config/routes.rb
Rails.application.routes.draw do
    resources :relationships,       only: [:create, :destroy]
  resources :images do
    resources :comments
    resources :likes
  end
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  resources :comments
  resources :likes
  root 'static_pages#home'
  get 'personal_page' => 'static_pages#personal_page'
  get 'users/:id' => 'users#show' 

  
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file, ImageUploader
	belongs_to :user
	has_many :comments
	has_many :likes

	def liked_by?(user)
     likes.exists?(user_id: user.id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    image = Image.find(params[:id])
    @comments = image.comments.all
    @comment = image.comments.build
    @current_user = current_user
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    respond_to do |format|
      if @image.save
        flash[:success] = "uploader success"
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        flash[:Danger] = "uploader errors"
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        flash[:success] = "update success"
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        flash[:Danger] = "update errors"
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      flash[:success] = "uploader success"
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id, :title, :file, :created_at)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image ,{multipart: true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
<div class="row">
  <div class="col-sm-8 well vitri-upanh box-shadow--4dp">
  
    <div class="field">
      <%= f.label 'title' %></br>
      <%= f.text_field :title,class: 'form-control' %>
    </div>
    <img id="img_prev" src="#" class="img-thumbnail hidden"/> <br/>
    
    <% if @image.file.nil? %>
    <div >
      <img id="img_prev" src="#" class="img-thumbnail hidden"/> <br/>
    </div>
    <%else%>
    <%= image_tag @image.file,class: "img-thumbnail" %>
    <%end%>
    
   <br/>
    <div class="field">
      <%= f.label 'choose file uploader' %></br>
      <%= f.file_field :file ,id: "img_prev2" %>
    </div>
    
      <%= f.submit "upload image",class: "btn btn-primary btn-block"  %>
    
  </div>
    
</div>
<% end %>

app/views/images/_like.html.erb
<%= form_for([image, image.likes.build], remote: true) do |f| %>
    <%= f.hidden_field :user_id %>
    <div>
    <%= image.likes.count %> likes
    </div>
    <button class="btn btn-primary" type="submit">Like</button>
<% end %>

app/views/images/_like_form.html.erb
<div id="like_form">
 <%if @image.liked_by?(current_user) %>
 	<%= render 'unlike' %>
 <%else %>
    <%= render 'like', image: @image %>
 <% end %>
 </div>

app/views/images/_unlike.html.erb
<%= form_for(@image.likes.find_by(user_id: current_user.id),
             html: { method: :delete },
             remote: true) do |f| %>
    <div>
    <%= @image.likes.count %> likes
    </div>
  <button class="btn btn-primary" type="submit">Unlike</button>
<% end %>

app/views/images/edit.html.erb
<h1 class="text-center">Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Destroy', @image, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Back', images_path %> 

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>String</th>
      <th>File</th>
      <th>String</th>
      <th>Created at</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.user_id %></td>
        <td><%= image.title %></td>
        <td><%= image.string %></td>
        <td><%= image.file %></td>
        <td><%= image.string %></td>
        <td><%= image.created_at %></td>
        <td><%= image.datetime %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div id="image-<%= @image.id %>">
<p id="notice"><%= notice %></p>
<div class="container">
  <h3 class="text-center">Show Image</h3>
  <div class="jumbotron">
    <div class="row">
      <div class="col-sm-4" >
        <strong>User:</strong>
        <%= @image.user.name %>
      </div>
      <div class="col-sm-4" >
        <strong>Title:</strong>
        <%= @image.title %>
      </div>
      <div class="col-sm-4" >
        <strong>Created at:</strong>
        <%= @image.created_at %>
      </div>
    </div>
    <%= image_tag @image.file,class: "img-thumbnail" %>
    <%= link_to 'Edit', edit_image_path(@image) %> |
    <%= link_to 'Back', images_path %>
  </div>
  <div id="likes">
  <%=render 'like_form'%>
  </div>
  <div id="comments">
  <%if @image.comments.any?%>
  <%= render @comments%>
  <%end%>
  </div>
  <div class="comment_form">
  <%= render 'shared/comment_form', image: @image %>
  </div>
</div>