config/routes.rb
Rails.application.routes.draw do
    resources :relationships,       only: [:create, :destroy]
  resources :images do
    resources :comments
    resources :likes
  end
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  resources :comments
  resources :likes
  root 'static_pages#home'
  get 'personal_page' => 'static_pages#personal_page'
  get 'users/:id' => 'users#show' 

  
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer-distributed">

			<div class="footer-left">

				<h3>Group<span>ichi</span></h3>

				<p class="footer-links">
					<a href="#">Home</a>
					·
					<a href="#">Blog</a>
					·
					<a href="#">Pricing</a>
					·
					<a href="#">About</a>
					·
					<a href="#">Faq</a>
					·
					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">Groupichi &copy; 2016</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>D9 đại học Bách Khoa Hà Nội</span> Hà Nội, Việt Nam</p>
					
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>01673203907</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@company.com">support@groupichi.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>Về chúng tôi</span>
					Tập hợp 5 sinh viên thuộc dự án Hedspi - Việt Nhật K57.
				</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>

				</div>

			</div>

		</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Flimage", root_path%></li>
      <% if user_signed_in? %>
      <li><%= link_to "trang cá nhân", personal_page_path %></li>
      <li><%= link_to "upload image" ,new_image_path%></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">account
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "change infomation",edit_user_registration_path %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete  %></li>
        </ul>
      </li>
    </ul>
      <% else %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "signin", user_session_path %>
        </li>
        <li>
          <!--span class="glyphicon glyphicon-user"></span-->
          <%= link_to "signup", new_user_registration_path %>
        </li>
      </ul>
      <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flimage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
	<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
</head>
<body>
<%= render 'layouts/nav' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>